trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'library-management-system'
  imageTag: '$(Build.BuildId)'
  outputFolder: 'docker_output'
  outputFile: 'lms-$(Build.BuildId).tar'
  remotePath: '/home/ec2-user/docker_images'
  containerName: 'lms-container'
  awsEc2SshConnection: 'aws-vm-ssh'
  ec2User: 'ec2-user'

steps:
  - checkout: self
    fetchDepth: 1
    displayName: 'Checkout repository'

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: 'Dockerfile'
      repository: '$(imageName)'
      tags: '$(imageTag)'
      arguments: '--no-cache'

  - script: |
      mkdir -p $(outputFolder)
      docker save -o $(outputFolder)/$(outputFile) $(imageName):$(imageTag)
    displayName: 'Save Docker Image as Tar File'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Docker Image Artifact'
    inputs:
      pathToPublish: '$(outputFolder)/$(outputFile)'
      artifactName: 'docker-image'
      publishLocation: 'Container'

  - task: CopyFilesOverSSH@0
    displayName: 'Copy Docker Image .tar to AWS EC2'
    inputs:
      sshEndpoint: '$(awsEc2SshConnection)'
      sourceFolder: '$(outputFolder)'
      contents: '$(outputFile)'
      targetFolder: '$(remotePath)'
      cleanTargetFolder: false
      overWrite: true

  - task: SSH@0
    displayName: 'Setup X11 and Run Docker Image on AWS EC2'
    inputs:
      sshEndpoint: '$(awsEc2SshConnection)'
      runOptions: 'inline'
      inline: |
        # Redirect output to a log file in ec2-user's home directory
        exec > /home/ec2-user/docker_deploy.log 2>&1
        
        # Ensure remote directory exists
        sudo mkdir -p $(remotePath) || { echo "Error: Failed to create directory $(remotePath)"; exit 1; }
        sudo chown ec2-user:ec2-user $(remotePath)
        echo "Directory $(remotePath) ensured."
        
        # Install Xvfb if not present
        echo "Checking X11 environment..."
        if ! command -v Xvfb > /dev/null; then
          echo "Installing Xvfb..."
          sudo dnf install -y xorg-x11-server-Xvfb || { echo "Error: Failed to install Xvfb."; exit 1; }
        fi
        
        # Start Xvfb if not running
        if ! pgrep Xvfb > /dev/null; then
          echo "Starting Xvfb on display :99..."
          sudo Xvfb :99 -screen 0 1024x768x16 &
          sleep 3
          if ! pgrep Xvfb > /dev/null; then
            echo "Error: Failed to start Xvfb."
            exit 1
          fi
          echo "Xvfb started successfully."
        else
          echo "Xvfb already running."
        fi
        export DISPLAY=:99
        echo "DISPLAY set to $DISPLAY"
        
        # Install and start tigervnc-server
        echo "Checking tigervnc-server installation..."
        if ! command -v vncserver > /dev/null; then
          echo "Installing tigervnc-server..."
          sudo dnf install -y tigervnc-server || { echo "Error: Failed to install tigervnc-server."; exit 1; }
        fi
        echo "Starting vncserver on display :99..."
        sudo pkill Xvnc || true
        sudo vncserver :99 -geometry 1024x768 -depth 16 -nolisten tcp -localhost no &
        sleep 2
        if ! pgrep Xvnc > /dev/null; then
          echo "Error: Failed to start vncserver."
          exit 1
        fi
        echo "vncserver started successfully."
        
        # Stop and remove existing container
        echo "Checking for existing container..."
        if sudo docker ps -a -q -f name=$(containerName); then
          echo "Stopping and removing container $(containerName)..."
          sudo docker stop $(containerName) || { echo "Error stopping container"; exit 1; }
          sudo docker rm $(containerName) || { echo "Error removing container"; exit 1; }
        else
          echo "No existing container found."
        fi
        
        # Remove existing image to avoid conflicts
        echo "Checking for existing image..."
        if sudo docker image inspect $(imageName):$(imageTag) > /dev/null 2>&1; then
          echo "Removing image $(imageName):$(imageTag)..."
          sudo docker rmi $(imageName):$(imageTag) || { echo "Error removing image"; exit 1; }
        else
          echo "No existing image found."
        fi
        
        # Load the new Docker image with retry
        echo "Loading image from $(remotePath)/$(outputFile)..."
        for attempt in {1..3}; do
          if sudo docker load -i $(remotePath)/$(outputFile); then
            echo "Image loaded successfully."
            break
          else
            echo "Attempt $attempt: Failed to load image."
            if [ $attempt -eq 3 ]; then
              echo "Error: Failed to load image after 3 attempts."
              exit 1
            fi
            sleep 2
          fi
        done
        
        # Run the container with X11 support for Tkinter
        echo "Starting container $(containerName)..."
        sudo docker run -d --name $(containerName) \
          -e DISPLAY=$DISPLAY \
          --network host \
          $(imageName):$(imageTag) || { echo "Error starting container"; exit 1; }
        
        echo "Container started successfully."
      readyTimeout: '60000'