trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'lms'
  imageTag: '$(Build.BuildId)'
  outputFolder: 'docker_output'
  outputFile: 'lms-$(Build.BuildId).tar'
  remotePath: '/home/$(vmUsername)/docker_images'
  containerName: 'lms-container'

steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
      repository: '$(imageName)'
      tags: '$(imageTag)'

  - script: |
      mkdir -p $(outputFolder)
      docker save -o $(outputFolder)/$(outputFile) $(imageName):$(imageTag)
    displayName: 'Save Docker image to tar'

  - task: CopyFilesOverSSH@0
    displayName: 'Copy Docker image to EC2'
    inputs:
      sshEndpoint: 'aws-vm-ssh'
      sourceFolder: '$(outputFolder)'
      contents: '$(outputFile)'
      targetFolder: '$(remotePath)'
      cleanTargetFolder: false
      overWrite: true

  - task: SSH@0
    displayName: 'Deploy Docker image on EC2'
    inputs:
      sshEndpoint: 'aws-vm-ssh'
      runOptions: 'commands'
      commands: |
        sudo mkdir -p $(remotePath)
        sudo docker load -i $(remotePath)/$(outputFile)
        sudo docker stop $(containerName) || true
        sudo docker rm $(containerName) || true
        sudo docker run -d --name $(containerName) -p 5000:5000 $(imageName):$(imageTag)
